cloud:
  aws:
    region:
      static: ap-southeast-1
      auto: false
    stack:
      auto: false
    credentials:
      accessKey:
      secretKey:

sendgrid:
  api:
    key:
mail:
  service:
    type: sendgrid